### ISSUE TITLE
DeepCell, CuCIM deps -- Build Scikit-image, Tensorflow for 2021b

### ISSUE THREAD

**Issue by c-gr34sl3y** [bear-rsg/bear-eb#132]
Ahead of PRs for INC1342020 could you build some of the larger deps for `2021b`?

These two are from upstream

- Archs - All **(not Ubuntu)**:

`scikit-image-0.19.1-foss-2021b.eb` 

https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/scikit-image/scikit-image-0.19.1-foss-2021b.eb

- Archs - Haswell/Icelake only

`TensorFlow-2.7.1-foss-2021b-CUDA-11.4.1.eb`

https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.7.1-foss-2021b-CUDA-11.4.1.eb

**Comment by branfosj** [comment]
`scikit-image-0.19.1-foss-2021b.eb`
* [ ] EL8-icelake
* [ ] EL8-cascadelake
* [ ] EL8-haswell

`TensorFlow-2.7.1-foss-2021b-CUDA-11.4.1.eb`
* [ ] EL8-icelake
* [ ] EL8-haswell
