### ISSUE TITLE
Build Miniconda3 and QIIME2

### ISSUE THREAD

**Issue by gyear** [bear-rsg/bear-eb#53]
For INC1302109 - `Miniconda3-4.12.0.eb QIIME2-2022.8.eb`

Default:
* [x] EL8-icelake
* [x] EL8-cascadelake
* [x] EL8-haswell

Use the command:
`eb --from-pr 16289 Miniconda3-4.12.0.eb QIIME2-2022.8.eb`

**Comment by orbsmiv** [comment]
Done
